---
title: "Class_Notes"
author: "MATEO BANDALA-JACQUES"
date: "2024-08-29"
output: html_document
---

```{r setup, include=FALSE}
library(reprex)
library(here)
library(tidyverse)
library(ggthemes)
library(bbplot)
library(ThemePark)
library(plotly)
library(colorblindr)
library(praise)

#remotes::install_github("clauswilke/colorblindr")

```

## Class notes for 2024-08-29

```{r cars}



print("hello world")


# reprex() will create a reproducible example of whatever is copied to the clipboard



here()
```


## Class notes for 2024-09-05

```{r}

#Let's create a tibble :) 


chicago <- readRDS(here("data", "chicago.rds"))
chicago <- as.tibble(chicago)

as.tibble(chicago) %>%
  print(n=30, width=Inf)

chicago$year <- lubridate::year(chicago$date)

chicago <- chicago %>%
  mutate(
    season = case_when(
      month(date) %in% c(12, 1, 2) ~ "Winter",
      month(date) %in% c(3, 4, 5) ~ "Spring",
      month(date) %in% c(6, 7, 8) ~ "Summer",
      month(date) %in% c(9, 10, 11) ~ "Fall"
    )
  )

chicago %>%
  ggplot(aes(x=date, y=tmpd, color=as.factor(season))) +
  geom_point() +
  labs(x="Date", y="Temperature, F", color="Season") +
  theme_minimal()

 glimpse(chicago)


tibble(
  a=1:5,
  b=6:10,
  c=1L
)

#Non-selecting some columns
chicago %>%
  select(-(city:dptp))


#And the equivalent using base R
i <- match("city", names(chicago))
j <- match("dptp", names(chicago))
head(chicago[, -(i:j)])




#Transmute drops all non-mutate variables


chicago %>%
  transmute(temp_c = (tmpd - 32) * 5 / 9)

chicago <- chicago %>%
  mutate(temp_c = (tmpd - 32) * 5 / 9)

chicago %>%
  group_by(year) %>%
  summarise(pm25 = mean(pm25tmean2, na.rm=TRUE),
            o3 = mean(o3tmean2, na.rm = TRUE),
            celsius = mean(temp_c, na.rm=TRUE))


# slice_sample shows a random subster of rows
set.seed(8963119)

chicago %>%
  slice_sample(n=5)
  


relig_income


relig_income %>%
  pivot_longer(-religion, names_to = "income", values_to = "response")






```

## Class notes for 2024-09-10

```{r notes 2024-09-10}


outcomes <- tibble(
  id = rep(c("a", "b", "c"), each=3),
  visit = rep(0:2,3),
  outcome = rnorm(3*3,3)
)


outcomes


subjects <- tibble(
  id = c("a", "b", "c"),
  house = c("detached", "rowhouse", "rowhouse")
)


subjects


left_join(outcomes, subjects, by="id")
 

full_join(outcomes, subjects, by="id")

inner_join(outcomes, subjects, by="id")


 
subjects <- tibble(
    id = c("b", "c"),
    visit = c(1, 0),
    house = c("rowhouse", "rowhouse"),
)

subjects



left_join(outcomes, subjects, by=c("id", "visit"))
 full_join(outcomes, subjects,  by=c("id", "visit"))
inner_join(outcomes, subjects,  by=c("id", "visit"))




semi_join(outcomes, subjects,  by=c("id", "visit"))
anti_join(outcomes, subjects,  by=c("id", "visit"))


```


``` {r ggplot stuff}

here()


maacs <- read_csv(here("data", "bmi_pm25_no2_sim.csv"),
    col_types = "nnci"
)

maacs

maacs %>%
  ggplot(aes(x=logpm25, y=NocturnalSympt)) +
  geom_point(aes(color=bmicat), alpha =10) +
  geom_smooth(method = "loess")+
  theme_stata(base_size = 20)




library(palmerpenguins)
library(bbplot)

penguins %>%
  ggplot(aes(x=flipper_length_mm, y=bill_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="glm") +
  labs(x=expression("Flipper lenght "[a]), y="Bill length", color="Species") +
  scale_x_continuous() +
  coord_cartesian(xlim=c(170,200))+ #This is a crop, not a true filter
  theme_bw()

  
  penguins %>%
  ggplot(aes(x=flipper_length_mm, y=bill_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="glm") +
  bbplot::bbc_style() + 
    labs(x=expression("Flipper lenght "[a]), y="Bill length", color="Species",
         title = "Penguins", subtitle = "Marica") 

  
g<-  penguins %>%
  ggplot(aes(x=flipper_length_mm, y=bill_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="glm") +
  theme_starwars()+
    labs(x=expression("Flipper lenght "[a]), y="Bill length", color="Species",
         title = "Penguins") 


    #Make it interactive
g<-  penguins %>%
  ggplot(aes(x=flipper_length_mm, y=bill_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="glm") +
  theme_starwars()+
    labs(x="FLipper length", y="Bill length", color="Species",
         title = "Penguins") 

plotly::ggplotly(g)



g<-  penguins %>%
  ggplot(aes(x=flipper_length_mm, y=bill_length_mm, color=species)) +
  geom_point() +
  geom_smooth(method="glm") +
    labs(x="FLipper length", y="Bill length", color="Species",
         title = "Penguins") 

colorblindr::cvd_grid(g)

```
## Class notes for 2024-09-17
```{r nuts and bolts}


x <- c("hola", seq(0,25,by=5), "gonorrhea")

class(x)

x


-15:15
for(i in x){
  print(x)
}


#Create an empty vector
vector(mode="numeric", length=4)
vector(mode="character", length=4)

#Create a non-empty vector

x <- c(0.5, 0.6) #numeric vector
x <- c(TRUE, FALSE) #logical vector
x <- c("a", "b") #character vector
x <- c(1+0i, 2+4i) #complex vector

#Atomic vectors can only contain objects of the same type/class
class(x)

# The exception is list: they allow you to have different classes of objects, and can be recursive

#Atomic vectors are homosexual, wile lists  can be heterosexual
list_object <-  list(1.5, "camila")
list_object

#If we do it with the c() function, it forces the 1.5 to be character, since vectors have to be the same class
class (c(1.5, "camila"))
class(list_object)



typeof(4) #Doubles are approximations
typeof(4L)



x <- sqrt(2)^2
x
x-2


letters
typeof(letters)
length(letters)
dim(letters)
typeof(letters)




typeof(c(TRUE,2))
typeof(c("a",TRUE))


#Explicit coercion
x <- 0:6
class(x)

as.numeric(x) #Stores as double
as.integer(x) #Stores as integer (better if no decimals)
as.logical(x) #1=TRUE, else = FALSE

#Sometimes R can't figure it out

x <- c("a", "b", "c")
as.numeric(x)


#Matrices

#matrixes are vectors with an extra dimension  :O

m <- matrix(nrow=2, ncol=3)
m

dim(m)

attributes(m)

#Matrices are constructed column-wise, starting top left


m <- matrix(1:6, nrow=2, ncol=3)
m



m <- matrix(c("Camila", "Restrepo", "Colombia", 
              "Mateo", "Jacques", "Mexico"),
            nrow=2, ncol=3, byrow = TRUE)

m



colnames(m) <- c("Nombre", "Apellido", "Páis")

m

as_tibble(m)

#Factors are objects that help us represent categories

x <- factor(c("yes", "no", "no", "yes", "yes"))
print(x)

table(x)



attributes(x)



x <- c(0,1,2,0,1,2,1,2,1,2,1,0,0)
x <- factor(x, levels = c(0,1,2), labels = c("No", "Yes", "Maybe"))
x
table(x)


x <- c(0,1,2,0,1,2,1,2,1,2,1,0,0)
x <- factor(x, levels = c(2,1,0), labels = c("Maybe", "Yes", "No"))
x
table(x)







#Dataframe

t <- tibble(
  Name = c("Camila", "Mateo", "Mitali"),
  Last_Name = c("Restrepo", "Jacques", "Joshi"),
  SSN = c(209568839,590204881,290652118)
)


t

```

#Notes for 2024-09-19

```{r}


x <- 3



if(x==3){
  print("Hi")
}


if (x==2){
  print("X = 2")
}else{
  print("X is not 2")
}


y <- ifelse(x==3, "It's 3", "Not 3")
y




for(i in 1:10){
  print(i)
}

x <- c("a", "b", "c", "d")

for (i in 1:4){
  print(i)
}


seq_along(x)

for (i in seq_along(x)) {
  print(i)
}

for (i in seq_along(x)) {
  print(i)
}


for (babyshark in x){
  print(babyshark)
}




#While

x <- 0 

while (x < 10){
  print(x)
  x <- x+1
  
}


#Next, and break
 for (i in 1:200){
   if (i <=20){
     ## skip the first 20 iterations
     next
   }
   print (i)
 }



#Next, and break
 for (i in 1:200){
   if (i >20){
     ## skip the first 20 iterations

   print (i)
   }}





#FUNCTIONS


f <- function(num){
  for (i in seq_len(num)){
    cat("Hello, world!\n")
  }
}


f(5)

```


## Notes for 2024-09-24
```{r}

inches <- c(69,62,66,70,70,73,67,73,67,70)

#if we wants to convert to centimeters:
inches

inches*2.54 #Each element is multiplied by 2.54

#Two vectors with the same length can be added


x<- 1:10
y <- 1:10


x+y


#that is, we don't need to write a for loop for thios




#' Title
#'
#' @param a 
#' @param b 
#'
#' @return
#' @export
#'
#' @examples
#' ##Let's show how to use my function
#' 
#'
my_sum <- function(a,b){
  if(length(a)!=length(b)){ stop("Vectors must be same length")}
  a+b
    c<-a+b
  print(c)
}



y <- 1:10
my_sum(x,y)


library(purrr)

purrr::map2_int(x,y, my_sum)



x<- list(a = 1:5, b=rnorm(10))
x


lapply(x, mean) # Output is a list

#or

map_dbl(x, mean) #Output is a vector




x <- c(rnorm(10), runif(10), rnorm(10,1))
x

f <- gl(3,10)
f


split(x,f)


lapply(split(x,f),mean)


#Splitting a data frame

library("datasets")
head(airquality)

#We can split de data by month

s<- split(airquality, airquality$Month)
str(s)


lapply(s, function(x) {
    colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm = TRUE)
})

sapply(s, function(x) {
    colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm = TRUE)
})




```



## Class notes for 2024-09-26
```{r}

sumsq <- function(mu, sigma, x) {
    sum(((x - mu) / sigma)^2)
}





x <- rnorm(100) ## Generate some data
x
sumsq(mu = 1, sigma = 1, x) ## This works (returns one value)


sumsq(1:10, 1:10, x) ## This is not what we want. ,we would want to try for mus 1 to 10



vsumsq <- Vectorize(sumsq, c("mu", "sigma"))
vsumsq(1:10, 1:10, x)




x <- data.frame(
    logic = c(TRUE, TRUE, FALSE),
    factor = factor(c("abc", "def", "ghi")),
    string = c("ABC", "DEF", "GHI"),
    real = c(1.23, -4.56, 7.89),
    cien.not = c(1.234e-23, -4.56 + 45, 7.89e78),
    date = as.Date(c("2012-02-21", "2013-02-12", "2014-03-04"))
)


x


log(-1)


print_message <- function(x) {
    if (x > 0) {
        print("x is greater than zero")
    } else {
        print("x is less than or equal to zero")
    }
    invisible(x)
}

print_message(NA)




print_message2 <- function(x) {
    if (is.na(x)) {
        print("x is a missing value!")
    } else if (x > 0) {
        print("x is greater than zero")
    } else {
        print("x is less than or equal to zero")
    }
    invisible(x)
}


print_message2(NA)

x <- log(c(-1, 2))

print_message2(x)



print_message3 <- function(x) {
    if (length(x) > 1L) {
        stop("'x' has length > 1", call. = FALSE)
    }
    if (is.na(x)) {
        print("x is a missing value!")
    } else if (x > 0) {
        print("x is greater than zero")
    } else {
        print("x is less than or equal to zero")
    }
    invisible(x)
}


print_message3(x)

praise()




is_even <- function(n){
   n%%2==0
}

is_even(874)

is_even_check <- function(n){
  is.numeric(n) & n%%2 ==0
}


is_even_check(3983)


```



## Notes for 2024-10-01

```{r}
library(lubridate)

help(package=lubridate)


mydate <- ymd("1993-02-28")

mydate+months(1)
mydate %m+% months(1)


#Learning to use da lubridate
today()
now()


ymd("1970-01-01")
ymd("2017-01-31")

mdy("January 1st, 2023")
mdy("June the 7th 2023")
mdy("It is June the 7th 2023") #Ay wow


dmy("31-Jan-2017")

#It's harder with base R

as.Date("January 31st, 2017", "%B %dst, %Y")

ymd(20170131) # そうですか

ymd("2016-09-13")
ymd("2016/09/13")
mdy("09-13-2016")

#Lubridate makes it work

x <- c("2016-04-05", "2016/05/06", "2016,10,4")
ymd(x)




#From individual date-time components

library(nycflights13)

flights

flights %>%
  select(year, month, day) %>%
  mutate(deprture = make_date(year, month, day))

flights %>%
  select(year, month, day) %>%
  mutate(deprture = make_date(year, month, day))


flights %>%
  select(year, month, day, dep_time) %>%
  mutate(hour = substr(dep_time,1,1), minute= substr(dep_time,2,3)) %>%
  mutate(hour = as.integer(hour), minute = as.integer(minute)) %>%
  mutate(deprture = make_datetime(year, month, day, hour, minute))



x <- today()

x-days(1)


#Date-Times in R
#Need to add an underscore


ymd_hms(now(), tz="America/New_York")





x <- ymd_hm("2024-09-23 23:00")
class(x)
unclass(x)

birthday <- ymd_hm("2025-05-29 19:00", tz="EST")
birthday

birthday <- ymd_hm("2025-05-29 19:00", tz="America/Monterrey")
birthday

wday(birthday, label = TRUE)
weekdays(birthday)




```



## Notes from 2024-10-3

```{r}
#Working with da string

#some strings
c("one", "two", "three")


#The grepl() function returns a logical vector if the pattern was found
# grepl(pattern, x)


regular_expression <- "a"
string_to_search <- c("Maryland", "Antonio", "Meep")

grepl(regular_expression, string_to_search, ignore.case = TRUE)
#a is in Maryland at least one


regular_expression <- "r.l"
string_to_search <- "Maryland"
grepl(regular_expression, string_to_search)


#Build some regular expressions to search the U.S states
head(state.name) #The 50 US States

# a Period (.) is anything but a new line

grepl(".", "Maryland")


#the dot only substitutes **one character**
grepl("a.b", c("aaa", "aab", "abb", "acadb"))


##REPETITION 
# + = One or more of the preceding, at least one time
# * = One or more of the preceding, at least zero times
# ? = Zero or 1 of the preceding

grepl("a+", "Maryland" ) #Maryland has "a" at least one time
grepl("x+", "Maryland") #No xs in Maryland

grepl("x*", "Mary;land") #Well, it does have an x at least zero times


#If we want the asterisk to modify more than one character, use a parenthesis

grepl("ax+", "Maryland")

#Does Maryland contain zero or more (ar) ?
grepl("(ar)*", "Maryland")



#Let's work with spookyhalloween

mytext <- "spookyhalloween"

#1) Does "zz" appear one or more times?
grepl("(zz)+", mytext)

#2) Does "ee" appear one or more times?
grepl("(ee)+", mytext)

#3) Does "oo" appear 0 or more times?
grepl("(oo)*", mytext)

#4) Does "ii" appear 0 or more times?
grepl("(ii)*", mytext)




# We can specify exact number of expressions using curly brackets

# {n} : exactly n
# {n,} : n or more
# {,m}: at most m
# {n,m} : between n and m

#a{5} is "a exactly 5 times"

#Does "Mississippi" contain exactly 2 adjacent "s"?

grepl("s{2}", "Mississippi")

#Does "Mississippi:" contain between 1 and 3 adjacent "s"?
grepl("s{1,3}", "Mississippi")

#Does "Mississippi:" contain between 1 and 3 adjacent "s"?
grepl("x{,3}", "Mississippi")


#does Mississsipii contain exactly 2 "iss"
grepl("(iss){2}", "Mississippi")

#Does Mississippi contain ss twice in a row?
grepl("(ss){2}", "Mississippi")





#Does Mississippi contain  
#"An i, followed by 2 characters (whichever)", three times
grepl("(i.{2}){3}", "Mississippi")


longer_text <- "spookyspookyhalloweenspookyspookyhalloween"

#1) #Search for spooky exactly 2 times
grepl("(spooky){2}", longer_text) # True! it contains a spookyspooky
grepl("(spooky){3}", longer_text) # False! No spookyspookyspooky

#2)  Search for 'spooky' exactly 2 times followed by any character length 9

grepl("(spooky){2}.{9}", longer_text)

#3) The same as above, twice in a row

grepl("((spooky){2}.{9}){2}", longer_text) #TRUE
grepl("((spooky){2}.{9}){3}", longer_text) #FALSE



# Character sets!


# words (\\w) = any letter, digit or underscore
# digits (\\d) = digits 0-9
# whitespace (\\s) = anything white space

#\\ is the opposuite


#If we want to search for a metacharacter, we need to use \\

grepl("\\+", "tragedy + time = humor") #This searches just for the plus
grepl("\\.", "https://publichealth.jhu.edu")





# \n new line
# \t new tab


x <- c("\\t", "\n", "\u00b5")
x
writeLines(x)



#Search for a word

grepl("\\w", "acbdef")




#Easier to specify in brackers

grepl("[aeiou]", "rythms") #Any of the vowels in rhythm
grepl("[A-Z|a-z|0-9]", "rythms") #Any of the vowels in rhythm
grepl("\\w", "rythms") #Any of the vowels in rhythm



grepl("[^aeiou]", "rythms") #Anything but a vowel



#All state names tha begin and end with a vowel


state.area


grepl("[aeiou]", state.name) #has a vowel

grepl("^[AEIOU]", state.name) #starts with vowel


grepl("^[AEIOU]{1}", state.name) #starts with exactly one vowel


grepl("^[AEIOU]{1}.+", state.name) #starts with exactly one vowel. and then anything else


grep("^[AEIOU]{1}.+[aeiou]{1}$", state.name) #starts and ends with vowel
grepl("^[AEIOU]{1}.+[aeiou]{1}$", state.name) #starts and ends with vowel



grep("[Ii]", c("Hawaii", "Maryland", "Kentucky"))


#Sub only replaces the first one
sub("[Ii]", "1", c("Hawaii", "Maryland", "Kentucky"))
#this changes all of them
gsub("[Ii]", "1", c("Hawaii", "Maryland", "Illinois"))








str_extract(state.area, "[0-9]+")
str_extract(state.area, "\\d+")



str_replace(state.name, "[Aa]", "B")
str_replace_all(state.name, "[Aa]", "B")


str_replace_all(state.name, "land", "stan")


```



## Notes from 2024-10-08
# Working with factors

```{r}

month_levels <- c(
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")




x <- c("Dec", "Apr", "Jan", "Mar")
x_typo <- c("Dec", "Apr", "Jam", "Mar")


y <- factor(x, levels = month_levels)
y


y <- factor(x_typo, levels = month_levels)
y



as.numeric(as.factor("hello")) #When it is turned into a factor, "1" is the first level

as.numeric(as.factor(c("hello", "goodbye")))




income_level <- c(
  rep("low", 10),
  rep("medium",10),
  rep ("high", 10)
)

x <- factor(income_level)
y <- rnorm(30)

lm(y~x) #But what if I wanted medium to be the reference?



levels(x)
x <- relevel(x, ref="medium")



# You wanna talk about factors? Let's talk about factors

library(forcats)

gss_cat %>% glimpse()


#When factors are stored in a tibble, you can see their levels like this:
gss_cat %>%
  count(race) 

gss_cat %>%
  ggplot(aes(x=race)) +
  geom_bar()

levels(gss_cat$race)
table(gss_cat$race, useNA = "ifany")




#Let's change the order of the levels
gss_cat %>%
  count(relig)
attributes(gss_cat$relig)



relig_summary <- gss_cat %>%
  group_by(relig) %>%
  summarise(
    tvhours = mean(tvhours, na.rm = TRUE,
                   n = n())
  )



relig_summary %>%
  ggplot(aes(x=tvhours,
             y= fct_reorder(relig, tvhours) )) +
  geom_point()

#but let's re-order



#different example

rincome_summary <- gss_cat %>%
  group_by(rincome) %>%
  summarise(
    age = mean(age, na.rm=TRUE),
    n=n()
  )


rincome_summary %>%
  ggplot(aes(x=age, y=rincome)) +
  geom_point()

#We could use fct_reorder()

rincome_summary %>%
  ggplot(aes(x=age, 
             y=fct_reorder(rincome,age))) +
  geom_point()

#But now the'yre not by intervals, so the other one was preferred

rincome_summary %>%
  ggplot(aes(x=age, y=rincome)) +
  geom_point()


#Let's practice 

penguins

#Calculate avg bill_length for each species

bill_info <- penguins %>%
  group_by(species) %>%
  summarise(avg_bill = mean(bill_length_mm, na.rm=TRUE))

bill_info  %>%
  mutate(species = fct_reorder(species, avg_bill)) %>%
  ggplot(aes(x=species, y=avg_bill)) +
  geom_point()


#Now fct_relevel

#Back to this one
rincome_summary %>%
  ggplot(aes(x=age, y=rincome)) +
  geom_point()

#We now set the first levels, and the rest remain
rincome_summary %>%
  ggplot(aes(x=age, y= fct_rev(fct_relevel(rincome, "Not applicable", "Refused")))) +
  geom_point()


rincome_summary %>%
  ggplot(aes(x=age, y= fct_relevel(rincome, "Not applicable", "Refused"))) +
  geom_point()

#There's a fct_reorder2()



by_age <- gss_cat %>%
  filter(!is.na(age))%>%
  count(age, marital)%>%
  group_by(age) %>%
  mutate(prop = n/sum(n))

by_age %>%
  ggplot(aes(x=age, y=prop, colour=marital)) +
  geom_line(na.rm=TRUE)



by_age %>%
  ggplot(aes(x=age, y=prop, 
             colour= fct_relevel(marital, "Separated", "Married"))) +
  geom_line(na.rm=TRUE) +
  labs(colour="Marital")



by_age %>%
  ggplot(aes(x=age, y=prop,
             colour = fct_reorder2(marital, age, prop))) +
  geom_line()

#For each category, for the highest level of X, it found the highest value of Y
#That is, at the end of follow-up, what was the proportion?




#fct_infreq() orders in decreasing frequency without the need for additional variables

gss_cat %>%
  mutate(marital = marital %>% fct_infreq() %>%fct_rev()) %>%
  ggplot(aes(x=marital)) +
  geom_bar()

gss_cat %>%
  count(partyid)

#New on theleft, old in the right

gss_cat %>%
  mutate(party = fct_recode(partyid,
         "Republican, strong" = "Strong, republican",
         "Republican, weak" = "Not str republican",
        "Independent, near rep" = "Ind,near rep",
        "Independent, near dem" = "Ind,near dem",
        "Democrat, weak"        = "Not str democrat",
        "Democrat, strong"      = "Strong democrat"
    )) %>%
    count(party)


#Actually, we want to combine


gss_cat %>% 
  mutate(partyid = fct_collapse(partyid,
    "Republican" = c("Strong republican", "Not str republican"),
    "Democrat" = c("Strong democrat", "Not str democrat"),
    "Independent" = c("Independent", "Ind,near dem" ,"Ind,near rep")
  )) %>%
  count(partyid)



#fct_lump_lowfreq() will lump low catwgories together into 'other' while keeping 'other' as the lowest


?fct_collapse
```


# *This is an example of addition of text*

## **This is an example of addition of text**

# ***This is an example of addition of text***


